#!/usr/bin/env python3
"""Validate Glasses Finder data relationships and shopper-facing invariants."""
from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_finder_capabilities import CAPABILITIES  # noqa: E402

MODEL_RE = re.compile(r"^\| (GLS-\d{4}) \|")
ALLOWED_STATES = {"yes", "no", "unknown", "na"}
ALLOWED_SOURCE_TYPES = {"manufacturer", "amazon", "major_retailer", "optical_retailer", "specialist_retailer", "secondary_market"}
ALLOWED_CONDITIONS = {"new", "refurbished", "used", "collector", "parts"}
LIVE_PRICE_AVAILABILITY = {"available"}
HISTORY_PRICE_AVAILABILITY = {"out_of_stock", "unavailable", "unknown"}


def load(path: str):
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def canonical_ids():
    ids = []
    for line in (ROOT / "models" / "THE_LIST.md").read_text(encoding="utf-8").splitlines():
        m = MODEL_RE.match(line)
        if m:
            ids.append(m.group(1))
    return ids


def validate_price_record(observation, idset, errors, ledger, allowed_availability):
    model_id = observation.get("id")
    if model_id not in idset:
        errors.append(f"{ledger} price observation references non-canonical ID {model_id}")
    try:
        if float(observation.get("price_usd")) <= 0:
            raise ValueError
    except (TypeError, ValueError):
        errors.append(f"{model_id} has invalid {ledger} price {observation.get('price_usd')!r}")
    if observation.get("availability") not in allowed_availability:
        errors.append(f"{model_id} has invalid {ledger} price availability {observation.get('availability')}; allowed={sorted(allowed_availability)}")
    if not observation.get("observed_at"):
        errors.append(f"{model_id} {ledger} price is missing observed_at")
    if not str(observation.get("source_url", "")).startswith("https://"):
        errors.append(f"{model_id} {ledger} price source is not https")


def fail(errors):
    print("Finder consistency check FAILED:")
    for error in errors:
        print(f"- {error}")
    raise SystemExit(1)


def main():
    errors = []
    ids = canonical_ids()
    idset = set(ids)
    if len(ids) != 145:
        errors.append(f"canonical Finder model count is {len(ids)}, expected 145")
    if len(idset) != len(ids):
        errors.append("canonical GLS IDs are not unique")

    schema = load("data/finder-schema.json")
    capability_fields = {
        f["field"]
        for group in schema.get("groups", [])
        for f in group.get("filters", [])
        if f.get("type") == "capability"
    }
    missing_fields = capability_fields - set(CAPABILITIES)
    if missing_fields:
        errors.append(f"Finder schema references capability fields not generated by matrix: {sorted(missing_fields)}")

    overrides = load("data/finder-capability-overrides.json")
    for record in overrides.get("records", []):
        if record.get("id") not in idset:
            errors.append(f"capability override references non-canonical ID {record.get('id')}")
        for field, value in record.get("capabilities", {}).items():
            if field not in CAPABILITIES:
                errors.append(f"{record.get('id')} override has unknown capability field {field}")
            state = value if isinstance(value, str) else value.get("value")
            if state not in ALLOWED_STATES:
                errors.append(f"{record.get('id')} {field} has invalid state {state!r}")

    purchase = load("data/purchase-sources.json")
    seen_purchase_ids = set()
    for record in purchase.get("records", []):
        model_id = record.get("id")
        if model_id not in idset:
            errors.append(f"purchase source references non-canonical ID {model_id}")
        if model_id in seen_purchase_ids:
            errors.append(f"duplicate purchase-source record for {model_id}")
        seen_purchase_ids.add(model_id)
        seen_urls = set()
        for source in record.get("sources", []):
            url = source.get("url", "")
            if not url.startswith("https://"):
                errors.append(f"{model_id} purchase URL is not https: {url}")
            if url in seen_urls:
                errors.append(f"{model_id} repeats purchase URL {url}")
            seen_urls.add(url)
            if source.get("source_type") not in ALLOWED_SOURCE_TYPES:
                errors.append(f"{model_id} has invalid purchase source type {source.get('source_type')}")
            if source.get("condition") not in ALLOWED_CONDITIONS:
                errors.append(f"{model_id} has invalid purchase condition {source.get('condition')}")

    live_prices = load("data/price-observations.json")
    for observation in live_prices.get("records", []):
        validate_price_record(observation, idset, errors, "live", LIVE_PRICE_AVAILABILITY)

    history_prices = load("data/price-history.json")
    for observation in history_prices.get("records", []):
        validate_price_record(observation, idset, errors, "history", HISTORY_PRICE_AVAILABILITY)

    live_keys = {(r.get("id"), r.get("source_url"), r.get("observed_at")) for r in live_prices.get("records", [])}
    history_keys = {(r.get("id"), r.get("source_url"), r.get("observed_at")) for r in history_prices.get("records", [])}
    duplicates = live_keys & history_keys
    if duplicates:
        errors.append(f"price observations appear in both live and history ledgers: {sorted(duplicates)}")

    with tempfile.TemporaryDirectory() as tmp:
        fallback_path = Path(tmp) / "purchase-fallbacks.json"
        subprocess.run([
            sys.executable, str(ROOT / "scripts" / "build_purchase_fallbacks.py"),
            "--models", str(ROOT / "models" / "THE_LIST.md"),
            "--curated", str(ROOT / "data" / "purchase-sources.json"),
            "--output", str(fallback_path),
        ], check=True)
        fallbacks = json.loads(fallback_path.read_text(encoding="utf-8"))
        fallback_records = {r["id"]: r.get("fallback") for r in fallbacks.get("records", [])}
        if set(fallback_records) != idset:
            errors.append("generated purchase fallback index does not cover exactly the canonical GLS IDs")
        curated_ebay = {
            r["id"]
            for r in purchase.get("records", [])
            if any("ebay." in s.get("url", "").lower() for s in r.get("sources", []))
        }
        missing_continuation = [mid for mid in ids if mid not in curated_ebay and not fallback_records.get(mid)]
        if missing_continuation:
            errors.append(f"models lack both curated and generated secondary-market continuation: {missing_continuation}")

    if errors:
        fail(errors)
    print(f"Finder consistency OK: {len(ids)} canonical models; live price filters exclude unavailable price history; every model has a secondary-market continuation path.")


if __name__ == "__main__":
    main()
